# Generated by Django 4.1.2 on 2022-10-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes", options={"verbose_name_plural": "Notes"},
        ),
    ]
