# Generated by Django 4.1.2 on 2022-10-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_homework"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homework", options={"verbose_name_plural": "Homework"},
        ),
        migrations.RenameField(
            model_name="homework", old_name="DueDate", new_name="due",
        ),
    ]
